#!/bin/bash
#
#  archsysinfo
#
#
#  Copyright 2012 Petronio Padilha <petroniopadilha@gmail.com>
#  
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.  
#  
#
#
kernVer=$(uname -m)
hostname=$([ -f /etc/hostname ] && cat /etc/hostname || cat /etc/rc.conf | grep HOSTNAME |cut -d'=' -f2)
kernelRelease=$(uname -r)
tempUptime=$(uptime | tr -s "," " " | awk '{print $1 " ("$3") " }')
contPacotes=$(pacman -Qq | wc -l)
memTotal=$(( $(cat /proc/meminfo | grep MemTotal: | cut -d: -f2 | awk '{print $1}') / 1024 ))
memUsed=$(( $(cat /proc/meminfo | grep Active: | cut -d: -f2 | awk '{print $1}') / 1024 ))
#procName=$(cat /proc/cpuinfo | grep "model name" | head -n1 | cut -d: -f2 | awk '{print $1,$2,$3}')
#procSpeed=$(cat /proc/cpuinfo | grep "model name" | head -n1 | cut -d: -f2 | awk '{print $4,$5,$6}')
procName=$(cat /proc/cpuinfo | grep "model name" | head -n1 | cut -d: -f2 | cut -d'@' -f1)
procSpeed=$(cat /proc/cpuinfo | grep "model name" | head -n1 | cut -d: -f2 | cut -d'@' -f2)
totalHd=$(df -h | grep rootfs | awk '{print $2}')
usadoHd=$(df -h | grep rootfs | awk '{print $3}')
totalUsado=$(df -h | grep rootfs | awk '{print $5}')
##$(df -h | grep rootfs | awk '{ print $3 " / " $2 " ("$5") " }')
editor=$EDITOR
dataAtual=$(date +%d/%m/%Y)
#
cvm='\033[01;31m'
cvr='\033[01;32m'
c1='\033[01;36m'
c2='\033[01;34m'
c0='\033[00m'
#
echo -e ""
echo -e "$c1               +                $c2 OS: $c0 Arch Linux $kernVer"
echo -e "$c1               #                $c2 Hostname: $c0 $hostname"
echo -e "$c1              ###               $c2 Kernel Release: $c0 $kernelRelease"
echo -e "$c1             #####              $c2 Uptime: $c0 $tempUptime"
echo -e "$c1             ######             $c2 Packages: $c0 $contPacotes"
echo -e "$c1            ; #####;            $c2 RAM: $cvr $memUsed MB $c0 / $memTotal MB"
echo -e "$c1           +##.#####            $c2 Processor Type: $c0 $procName"
echo -e "$c1          +##########           $c2 Processor Speed: $c0 $procSpeed"
echo -e "$c1         ######$c2#####$c1##;         $c2 \$EDITOR: $c0 $editor"
echo -e "$c1        ####$c2##########$c1#+        $c2 Root: $cvm $usadoHd $c0/ $totalHd ($totalUsado)"
echo -e "$c1       ###$c2####   #######    "
echo -e "$c1     .##$c2####;     ;####;\". "
echo -e "$c1    .#$c2######;     ;#####.   "
echo -e "$c2    #########.   .########'    "
echo -e "$c2   ######'           '######   "
echo -e "$c2  ;####                 ####;  "
echo -e "$c2  ##'                     '##  "
echo -e "$c2 #'                         '# "
echo -e "$c0"


##EOF